### ISSUE TITLE
Not a Issue!

### ISSUE THREAD

**Issue by FischiTheDev** [l4zs/minecraft-start-bat-creator#4]
I saw the project and I was wondering cause im german, I could help for translating the file into german if thats possible.

**Comment by l4zs** [comment]
thanks for the offer but as I am a native german as well I don't need any help on translating it, the reason why it hasn't been translated so far is basically that I didn't want to write batch

**Comment by NyCodeGHG** [comment]
> I saw the project and I was wondering cause im german, I could help for translating the file into german if thats possible.

If you really need a translation, you could use [mcserv](https://github.com/DRSchlaubi/mcserv) which provides german translations.
**Note: I'm a contributor of that project.**
(But i also contributed here 😜)
