### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Karhuukki** [l4zs/minecraft-start-bat-creator#7]
DISPLAY: 'Download latest paper-1.16.5.jar' TYPE: DOWNLOAD STATE: TRANSIENT_ERROR
PRIORITY: NORMAL FILES: 0 / 1 BYTES: 0 / UNKNOWN
ERROR FILE:    https://papermc.io/api/v1/paper/1.16.5/latest/download -> C:\Users\Markus\Dropbox\Mein PC (DESKTOP-PQQR3
ERROR CODE:    0x80200059
ERROR CONTEXT: 0x00000002

**Comment by l4zs** [comment]
Don't run this bat inside of a dropbox

**Comment by DRSchlaubi** [comment]
I think you should use http://mcserv.how instead

**Comment by DRSchlaubi** [comment]
> DISPLAY: 'Download latest paper-1.16.5.jar' TYPE: DOWNLOAD STATE: TRANSIENT_ERROR PRIORITY: NORMAL FILES: 0 / 1 BYTES: 0 / UNKNOWN ERROR FILE: https://papermc.io/api/v1/paper/1.16.5/latest/download -> C:\Users\Markus\Dropbox\Mein PC (DESKTOP-PQQR3 ERROR CODE: 0x80200059 ERROR CONTEXT: 0x00000002

don't download bat files from the internet they could harm your pc

**Comment by l4zs** [comment]
> > DISPLAY: 'Download latest paper-1.16.5.jar' TYPE: DOWNLOAD STATE: TRANSIENT_ERROR PRIORITY: NORMAL FILES: 0 / 1 BYTES: 0 / UNKNOWN ERROR FILE: https://papermc.io/api/v1/paper/1.16.5/latest/download -> C:\Users\Markus\Dropbox\Mein PC (DESKTOP-PQQR3 ERROR CODE: 0x80200059 ERROR CONTEXT: 0x00000002
> 
> don't download bat files from the internet they could harm your pc

they could, won't do it tho.

Anyways as this bat isn't the best and pretty outdated, I recommend using
https://docs.mcserv.how/install/ instead, have a look at that @Karhuukki
